# Generated by Django 4.1.7 on 2023-04-01 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pokemon',
            table='pokemon',
        ),
        migrations.AlterModelTable(
            name='pokemontypes',
            table='pokemon_types',
        ),
    ]
